# Generated by Django 5.0.14 on 2025-12-11 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_live_chat_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_channel_id', models.CharField(blank=True, max_length=255)),
                ('message_text', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'Baru'), ('reviewed', 'Ditinjau'), ('sent', 'Terkirim'), ('ignored', 'Diabaikan')], default='new', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comments.livestream')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
