# Generated by Django 5.0.14 on 2025-12-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='next_page_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
