# Generated by Django 5.0.14 on 2025-12-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_livestream_last_polled_at_livestream_next_page_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='obs_host',
            field=models.CharField(blank=True, help_text='OBS websocket host, e.g. 127.0.0.1', max_length=255),
        ),
        migrations.AddField(
            model_name='livestream',
            name='obs_password',
            field=models.CharField(blank=True, help_text='OBS websocket password (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='livestream',
            name='obs_port',
            field=models.PositiveIntegerField(blank=True, help_text='OBS websocket port, e.g. 4444', null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='obs_text_source',
            field=models.CharField(blank=True, help_text='Name of text source in OBS to update', max_length=255),
        ),
    ]
