# Generated by Django 5.0.14 on 2025-12-15 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_livestream_obs_host_livestream_obs_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this OBS connection', max_length=128, unique=True)),
                ('host', models.CharField(help_text='OBS websocket host, e.g. 127.0.0.1', max_length=255)),
                ('port', models.PositiveIntegerField(default=4444, help_text='OBS websocket port')),
                ('password', models.CharField(blank=True, help_text='OBS websocket password (optional)', max_length=255)),
                ('default_text_source', models.CharField(blank=True, help_text='Default text source name in OBS', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='obs_host',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='obs_password',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='obs_port',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='obs_text_source',
        ),
        migrations.AddField(
            model_name='livestream',
            name='obs_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to='comments.obsconfig'),
        ),
    ]
