# Generated by Django 5.0.14 on 2025-12-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_obsconfig_remove_livestream_obs_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatmessage',
            name='author_profile_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
