# Generated by Django 5.0.14 on 2025-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_livechatmessage_author_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatmessage',
            name='obs_selected',
            field=models.BooleanField(default=False),
        ),
    ]
