# Generated by Django 5.0.14 on 2025-12-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_livechatmessage_obs_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='obs_config',
        ),
        migrations.RenameField(
            model_name='livechatmessage',
            old_name='obs_selected',
            new_name='display_selected',
        ),
        migrations.AddField(
            model_name='livestream',
            name='display_rotation_seconds',
            field=models.PositiveIntegerField(default=6, help_text='Seconds each comment is shown in the display'),
        ),
        migrations.DeleteModel(
            name='OBSConfig',
        ),
    ]
