# Generated by Django 5.0.14 on 2025-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_livestream_obs_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageableLiveChatMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Manageable live chat message',
                'verbose_name_plural': 'Manageable live chat messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('comments.livechatmessage',),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='display_order',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
