# Generated by Django 5.2.9 on 2026-01-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_manageablelivechatmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manageablelivechatmessage',
            options={'verbose_name': 'Manage live chat', 'verbose_name_plural': 'Manage live chat'},
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='display_rotation_seconds',
            field=models.PositiveIntegerField(default=15, help_text='Seconds each comment is shown in the display'),
        ),
    ]
