# Generated by ChatGPT on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("comments", "0009_alter_manageablelivechatmessage_options_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="livestream",
			name="display_limit",
			field=models.PositiveIntegerField(
				default=100,
				help_text="Max number of messages kept in display rotation (excluding pinned)",
			),
		),
	]
